### ISSUE TITLE
Server disconnected while disabling alarm

### ISSUE THREAD

**Issue by quelqundev** [quelqundev/NexecurScheduler#22]
The scheduler has to be implemented to retry the disable job if the first try failed because of no Internet connection. Indeed we can't send SMS to alert that alarm is still enabled...that's why we have to try to disable as soon as possible !

**Comment by baudev** [comment]
Unless I'm wrong, this issue is the same as https://github.com/quelqundev/NexecurScheduler/issues/11

**Comment by quelqundev** [comment]
That's not the same issue but : one is about electrical blackout and means handling RPi reboot, the other is handling the network failure.
